added actions and props for cycling through blue,brown,green,grey
streamplace/tile-monster pull request #1
Opened 2017-08-07 02:31 UTC by acatmore

2017-08-07 03:01 UTC, iameli requested changes
Two changes, looks fine otherwise

2017-08-07 03:01 UTC, iameli commented on src/Cell.js
> +    console.log("hi");
that's very friendly but not terribly necessary

2017-08-07 03:01 UTC, iameli commented on src/actions.js
> +export const turnBlue = (x, y, clickedNum) => {
I don't think `clickedNum` is necessary in the actions. Evidence: you're not actually providing the argument in these actions and everything works fine.

![image](https://user-images.githubusercontent.com/257909/29010678-e0d25ade-7ae1-11e7-8d59-82632166e13b.png)

Seems like the reducer is taking care of it.

2017-08-07 06:24 UTC, acatmore commented on src/actions.js
> +export const turnBlue = (x, y, clickedNum) => {
I see. Was wondering about that. I had it set it up before I had the prop built in from the reducer

2017-08-08 00:47 UTC, iameli approved these changes

2017-08-08 00:47 UTC, merged